- name: install haproxy
  apt:
    name: haproxy
    state: present

- name: copy haproxy cfg
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: reload haproxy servc
  service:
    name: haproxy
    state: reloaded
