---
- hosts: servers
  become: yes
  tasks:
  - name: place ssh keys
    authorized_key:
      user: user
      key: https://github.com/saudzi.keys

  - name: sudo no pass
    copy:
      dest: /etc/sudoers.d/user
      content: "user	ALL = NOPASSWD: ALL"

  - name: Setup interface
    template:
      src: ./enp0s8
      dest: /etc/netplan/55-enp0s8.yaml
      notify:
          - netplan apply

   handlers:
    - name: netplan apply
      shell: netplan apply

