- name: docker worpress container
  docker_container:
    name: "{{ container_name }}"
    image: wordpress
    state: started
    network_mode: bridge
    ports: "{{ host_port }}:80"
    detach: true
    restart_policy: always
    env:
      WORDPRESS_DB_HOST: "{{mysql_server}}:{{mysql_port}}"
      WORDPRESS_DB_USER: "{{mysql_user}}"
      WORDPRESS_DB_NAME: "{{mysql_db}}"
      WORDPRESS_DB_PASSWORD: "{{mysql_pass}}"
