- name: register timestamp 
  shell: date +%s
  register: ts

- name: configure bind
  template:
    src: db.sleep
    dest: /etc/bind/db.sleep
    
- name: configure bind pointer 
  template:
    src: db.sleep.ptr
    dest: /etc/bind/db.sleep.ptr

- name: restart bind
  service:
    name: bind9
    state: restarted

- name: reload db
  shell: rndc reload 

- name: checkconf
  shell: named-checkconf
