- name: install packages
  apt:
    package: "{{ item }}"
  with_items:
    - adduser
    - libfontconfig1

- name: download  grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_6.4.4_amd64.deb
    dest: /opt/grafana_6.4.4_amd64.deb

- name:  install grafana
  apt:
    deb: /opt/grafana_6.4.4_amd64.deb


- name: grafana service start
  service:
    name: grafana-server
    state: started
    enabled: yes
