return2: 1 #if you want to return only 1 server edit it to non-1 value
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
locals:
  - 192.168.56.0/24
  - 127.0.0.0/24

dns_records:
  - type: NS
    entries:
      - name: no.sleep.
        address: server1.no.sleep.
      - name: no.sleep.
        address: server2.no.sleep.
  - type: A
    entries:
      - name: server1.no.sleep.
        address: 192.168.56.5
      - name: server2.no.sleep.
        address: 192.168.56.6
      - name: servers.no.sleep.
        addresses:
          - 192.168.56.5

  - type: CNAME
    entries:
      - name: ns
        address: servers.no.sleep.
      - name: ns1
        address: server1.no.sleep.
      - name: ns2
        address: server2.no.sleep.
