
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
locals:
  - 192.168.56.0/24
  - 127.0.0.0/24
dns_records:
  - name: no.sleep.
    type: NS
    address: server1.no.sleep.

  - name: no.sleep.
    type: NS
    address: server2.no.sleep.

  - name: server1.no.sleep.
    type: A
    address: 192.168.56.5

  - name: server2.no.sleep.
    type: A
    address: 192.168.56.6

  - name: influxdb.no.sleep.
    type: A
    address: 192.168.56.6

  - name: ns1.no.sleep.
    type: CNAME
    address: server1.no.sleep.

  - name: ns2.no.sleep.
    type: CNAME
    address: server2.no.sleep.
