---
- name: part1
  hosts: server1
  become: yes
  tasks:
  - name: installing apache
    package:
      name: apache2
      state: present

  - name: \copy wordpress config
    template:
      src: ./files/wordpress.conf
      dest: /etc/apache2/sites-enabled/wordpress.conf

  - name: copy apache cfg
    template:
      src: ./files/000-default.conf
      dest: /etc/apache2/sites-enabled/000-default.conf

  - name:  get php
    package:
      name: php
      state: present

  - name: get wordpress
    package:
      name: wordpress
      state: present

  - name: wordpress config 
    template:
      src: ./files/config-localhost.php
      dest: /etc/wordpress/config-168.56.5.php

  - name: reload apache
    service:
      name: apache2
      state: reloaded



- name: part2
  hosts: server2
  become: yes
  tasks:
  - name: get mysql
    package:
      name: mysql-server
      state: present

  - name: copy mysql cfg
    template:
      src: ./files/mysqld.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf

  - name: make db file
    template:
      src: ./files/database.sql
      dest: /tmp/database.sql

  - name: create db and user
    shell: mysql --defaults-file=/etc/mysql/debian.cnf < /tmp/database.sql

  - name: reload mysql
    service:
      name: mysql
      state: restarted

  - name: Remove file
    file:
      path: /tmp/database.sql
      state: absent
