- name: install mysql
  package:
    name: mysql-server 
    state: present

- name: copy mysql cfg
  template:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf

- name: copy db file
  template:
    src: database.sql
    dest: /tmp/database.sql

- name: mysql user
  shell: mysql --defaults-file=/etc/mysql/debian.cnf < /tmp/database.sql

- name: reload mysql service
  service:
    name: mysql
    state: restarted

- name: Remove file
  file:
    path: /tmp/database.sql
    state: absent
