---
- name: Lab3
  hosts: saxeli
  become: yes
  tasks:
  - name: Ping
    ping:

  - name: installing Apache
    package:
      name: apache2
      state: present

  - name: installing PHP
    package:
      name: php
      state: present

  - name: update ports
    copy:
      src: ./files/ports.conf
      dest: /etc/apache2/ports.conf

  - name: make php document
    copy:
      src: ./files/php-8080.conf
      dest: /etc/apache2/sites-enabled/php-8080.conf

  - name: make index.php
    copy:
      src: ./files/index.php
      dest: /var/www/php/

  - name: reload
    service:
      name: apache2
      state: reloaded
