
- name: get mysql
  package:
    name: mysql-server
    state: present

- name: copy mysql cfg
  template:
    src: ./files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf


- name: myql server and py3
  package:
    name: ['mysql-server', 'python3-pip','python-mysqldb']
    state: present

- pip:
    name: ['PyMySQL']

- name: make database
  mysql_db:
    name: "{{mysql_db}}"
    state: present
   
- name: create db user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_pass }}"
    priv: '*.*:ALL'
    host: "%"
    state: present
  notify: restart mysql
