---
- name: node_exporter
  hosts: servers
  become: yes
  vars:
    node_exporter_user: node_exporter
    bind_exporter_user: bind_exporter
  roles: 
    - node_exporter

- name: prometheus
  hosts: server2
  become: yes
  vars:
     version: 2.14.0
     prometheus_user: root
     mysql_exporter_user: mysql_exporter
     mycnf_dest: /home/mysql_exporter/
     apache_exporter_user: apache_exporter
  roles:
    - prometheus
    - grafana importer
    - mysql_exporter
    - apache exporter

- name: bind exporter
  hosts: servers
  become: yes
  vars:
    node_exporter_user: node_exporter
    bind_exporter_user: bind_exporter
  roles:
    - bind exporter
